name: C/C++ CI

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: build-static-with-db48-openssl102
      run: cd contrib && ./build-static-with-db48.sh
